name: 'Main Merge'

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - main

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full clone necessary for proper merge

      - name: Nightly Merge
        uses: robotology/gh-action-nightly-merge@v1.5.2
        with:
          stable_branch: 'main'
          development_branch: 'develop'
          allow_ff: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}